# Generated by Django 2.1 on 2018-09-03 22:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(max_length=1000)),
                ('tech_used', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sub_description', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project_link', models.URLField(max_length=100)),
                ('project_date', models.DateTimeField(verbose_name='project date')),
                ('project_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
