# Generated by Django 2.1 on 2018-09-08 01:03

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_description',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PM', 'Product Manager'), ('WD', 'Web Developer'), ('ML', 'Machine Learning')], default='WD', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_used',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
