# Generated by Django 2.1 on 2018-09-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180908_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PM', 'Product Manager'), ('WD', 'Web Developer'), ('ML', 'Machine Learning'), ('GD', 'Game Developer')], default='WD', max_length=2),
        ),
    ]
