# Generated by Django 2.1 on 2018-09-07 16:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180830_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='primary_photo',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
    ]
